---
name: ShowPerms
version: 2.0.0
authors:
  - ethaniccc
  - mmm545
main: ethaniccc\ShowPerms\Main
api: 4.0.0
commands:
 showperms:
  description: Show all the permission nodes!
  permission: showperms.command

permissions:
  showperms.command:
    default: op
    description: Gives permission to show all the permission nodes
...
